version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    environment:
      CI: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'

      - run:
          name: Run tests
          command: yarn test --ci --coverage --maxWorkers=2

workflows:
  version: 2
  Build and Test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
